version: "2"
linters:
    # inverted configuration with `default: all` and `disable` is not scalable during updates of golangci-lint
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - ginkgolinter
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

  # to be checked:
  # - errorlint
  # - forbidigo
  # - forcetypeassert
  # - goerr113
  # - ifshort
  # - nilerr
  # - nlreturn
  # - noctx
  # - nolintlint
  # - paralleltest
  # - promlinter
  # - tagliatelle
  # - wrapcheck

  # don't enable:
  # - cyclop
  # - depguard
  # - exhaustive
  # - exhaustivestruct
  # - funlen
  # - gochecknoglobals
  # - gochecknoinits
  # - godot
  # - godox
  # - gomnd
  # - testpackage
  # - 
  
  settings:
    lll:
      line-length: 120
  exclusions:
    generated: lax
    rules:
      # Allow dot imports for ginkgo and gomega
      - linters:
          - revive
        text: should not use dot imports
        source: ginkgo|gomega
      # Exclude some linters from running on tests files.
      - linters:
          - goconst
        path: _test\.go
      # Exclude lll issues for lines with long annotations
      - linters:
          - lll
        source: //\s*\+
    paths:
      - zz_generated.*
      - internal/operator/controller/suite_test.go
      # Those tests are generated by kubebuilder
      - test
      # Added by "golangci-lint migrate", to be removed?
      - third_party$
      - builtin$
      - examples$
  
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/operasoftware/cnpg-plugin-pgbackrest)
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - zz_generated.*
      - internal/operator/controller/suite_test.go
      # Those tests are generated by kubebuilder
      - test
      # Added by "golangci-lint migrate", to be removed?
      - third_party$
      - builtin$
      - examples$
