apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-example
spec:
  method: plugin

  cluster:
    name: cluster-example
  # Currently only primary is supported.
  target: primary

  pluginConfiguration:
    name: pgbackrest.cnpg.opera.com
    parameters:
      type: full

