# permissions for end users to edit archives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: plugin-pgbackrest
    app.kubernetes.io/managed-by: kustomize
  name: archive-editor-role
rules:
- apiGroups:
  - pgbackrest.cnpg.opera.com
  resources:
  - archives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgbackrest.cnpg.opera.com
  resources:
  - archives/status
  verbs:
  - get
