//go:build !ignore_autogenerated

/*
Copyright 2025, Opera Norway AS

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package api

import (
	pkgapi "github.com/cloudnative-pg/machinery/pkg/api"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataBackupConfiguration) DeepCopyInto(out *DataBackupConfiguration) {
	*out = *in
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = new(int32)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdditionalCommandArgs != nil {
		in, out := &in.AdditionalCommandArgs, &out.AdditionalCommandArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataBackupConfiguration.
func (in *DataBackupConfiguration) DeepCopy() *DataBackupConfiguration {
	if in == nil {
		return nil
	}
	out := new(DataBackupConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgbackrestConfiguration) DeepCopyInto(out *PgbackrestConfiguration) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]PgbackrestRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Wal != nil {
		in, out := &in.Wal, &out.Wal
		*out = new(WalBackupConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(DataBackupConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgbackrestConfiguration.
func (in *PgbackrestConfiguration) DeepCopy() *PgbackrestConfiguration {
	if in == nil {
		return nil
	}
	out := new(PgbackrestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgbackrestCredentials) DeepCopyInto(out *PgbackrestCredentials) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(S3Credentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgbackrestCredentials.
func (in *PgbackrestCredentials) DeepCopy() *PgbackrestCredentials {
	if in == nil {
		return nil
	}
	out := new(PgbackrestCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgbackrestRepository) DeepCopyInto(out *PgbackrestRepository) {
	*out = *in
	in.PgbackrestCredentials.DeepCopyInto(&out.PgbackrestCredentials)
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
	if in.EndpointCA != nil {
		in, out := &in.EndpointCA, &out.EndpointCA
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(PgbackrestRetention)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgbackrestRepository.
func (in *PgbackrestRepository) DeepCopy() *PgbackrestRepository {
	if in == nil {
		return nil
	}
	out := new(PgbackrestRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgbackrestRetention) DeepCopyInto(out *PgbackrestRetention) {
	*out = *in
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgbackrestRetention.
func (in *PgbackrestRetention) DeepCopy() *PgbackrestRetention {
	if in == nil {
		return nil
	}
	out := new(PgbackrestRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Credentials) DeepCopyInto(out *S3Credentials) {
	*out = *in
	if in.AccessKeyIDReference != nil {
		in, out := &in.AccessKeyIDReference, &out.AccessKeyIDReference
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
	if in.SecretAccessKeyReference != nil {
		in, out := &in.SecretAccessKeyReference, &out.SecretAccessKeyReference
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Credentials.
func (in *S3Credentials) DeepCopy() *S3Credentials {
	if in == nil {
		return nil
	}
	out := new(S3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WalBackupConfiguration) DeepCopyInto(out *WalBackupConfiguration) {
	*out = *in
	if in.ArchiveAdditionalCommandArgs != nil {
		in, out := &in.ArchiveAdditionalCommandArgs, &out.ArchiveAdditionalCommandArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RestoreAdditionalCommandArgs != nil {
		in, out := &in.RestoreAdditionalCommandArgs, &out.RestoreAdditionalCommandArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WalBackupConfiguration.
func (in *WalBackupConfiguration) DeepCopy() *WalBackupConfiguration {
	if in == nil {
		return nil
	}
	out := new(WalBackupConfiguration)
	in.DeepCopyInto(out)
	return out
}
