apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgbackrest
  name: pgbackrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbackrest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgbackrest
    spec:
      serviceAccountName: plugin-pgbackrest
      containers:
      - image: plugin-pgbackrest:latest
        name: pgbackrest
        ports:
        - containerPort: 9090
          protocol: TCP
        env:
        - name: SIDECAR_IMAGE
          valueFrom:
            secretKeyRef:
              key: SIDECAR_IMAGE
              name: plugin-pgbackrest
        args:
        - operator
        - --server-cert=/server/tls.crt
        - --server-key=/server/tls.key
        - --client-cert=/client/tls.crt
        - --server-address=:9090
        - --leader-elect
        - --log-level=debug
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - mountPath: /server
          name: server
        - mountPath: /client
          name: client
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
      volumes:
      - name: server
        secret:
          secretName: pgbackrest-server-tls
      - name: client
        secret:
          secretName: pgbackrest-client-tls
