apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgbackrest
    cnpg.io/pluginName: pgbackrest.cnpg.opera.com
  annotations:
    cnpg.io/pluginClientSecret: pgbackrest-client-tls
    cnpg.io/pluginServerSecret: pgbackrest-server-tls
    cnpg.io/pluginPort: "9090"
  name: pgbackrest
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: pgbackrest
